"""Regenerate ``examples/fixtures/R*.answers.json`` from the demo scripts (:mod:`jevtools.demo.scripts`), and the
proxy example's source files ``examples/proxy/data/*.json`` from the demo world (:mod:`jevtools.demo.scenario`).

    python examples/fixtures/regenerate.py           # (re)write the files
    python examples/fixtures/regenerate.py --check   # exit 1 when a file is missing or stale

Each file is in the :meth:`ScriptedBackend.from_fixture <jevtools.backends.ScriptedBackend.from_fixture>` format:
``{"note", "request", "model", "answers": {qid-or-glob: answer}}`` for a static script, or ``{…, "rounds": [{…},
…]}`` (one script per Jev request, in order) for the scripts that compute answers from the request (the R4 bucket
hit, the two R6 agent steps): those are replayed once over the demo world and every asked question's answer is
recorded. ``helpdesk.answers.json`` (example 08) is written by hand and left alone.

The numbers are the spec's illustrative [I] answers: they exercise plumbing and policy branches and are never
evidence about Jev's accuracy.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import sys
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jevtools.demo import scenario, scripts
from jevtools.loop import Agent
from jevtools.wire import DecisionRequest

HERE = Path(__file__).resolve().parent
PROXY_DATA = HERE.parent / "proxy" / "data"
NOTE = ("Illustrative [I] Jev answers of the spec §13 walk-through ({what}); generated by "
        "examples/fixtures/regenerate.py from jevtools.demo.scripts. Scripted answers are never evidence about "
        "Jev's accuracy.")  # fmt: skip

ScriptFn = Callable[[DecisionRequest], Mapping[str, Any]]


@dataclass(frozen=True)
class Case:
    """One fixture: a static ``answers`` script, or a ``runner`` that replays a callable script and returns the
    per-request answers."""

    what: str
    request: str
    answers: Mapping[str, Any] | None = None
    runner: Callable[[], list[dict[str, Any]]] | None = None
    rounds: tuple[Mapping[str, Any], ...] = ()


def lookup(script: Mapping[str, Any], qid: str) -> Any:
    """The answer a script gives ``qid`` (exact id first, then the first matching glob), as ScriptedBackend does."""
    if qid in script:
        return script[qid]
    return next((spec for pattern, spec in script.items() if any(c in pattern for c in "*?[")
                 and fnmatch.fnmatchcase(qid, pattern)), None)  # fmt: skip


class Recorder:
    """Wraps a callable script and records, per request, the answer of every question it asks."""

    def __init__(self, script: ScriptFn) -> None:
        self.script = script
        self.rounds: list[dict[str, Any]] = []

    def __call__(self, request: DecisionRequest) -> Mapping[str, Any]:
        answers = self.script(request)
        recorded = {qid: lookup(answers, qid) for qid in request.questions}
        self.rounds.append({qid: spec for qid, spec in recorded.items() if spec is not None})
        return answers


def record_r4_bucket_hit() -> list[dict[str, Any]]:
    recorder = Recorder(scripts.r4_found_in_bucket)
    router, _ = scenario.scenario_router(recorder)
    router.decide(scenario.scenario_messages(scripts.R4_REQUEST))
    return recorder.rounds


def record_r6(step2: Mapping[str, Any]) -> Callable[[], list[dict[str, Any]]]:
    def run() -> list[dict[str, Any]]:
        recorder = Recorder(scripts.r6_script(step2))
        router, _ = scenario.scenario_router(recorder)
        agent = Agent(router, scenario.Workspace().executors())
        result = agent.run(scripts.R6_REQUEST)
        if result.pending is not None:
            agent.resume(result.pending, selection="ok")
        return recorder.rounds

    return run


CASES: dict[str, Case] = {
    "R1": Case("R1, weather in Fahrenheit", scripts.R1_REQUEST, scripts.R1),
    "R1-dropin": Case("R1 as a drop-in loop: the weather call, then DONE once the tool result is back",
                      scripts.R1_REQUEST, rounds=(scripts.R1, scripts.R1_DONE)),
    "R2": Case("R2 with history: confirm", scripts.R2_REQUEST, scripts.R2),
    "R2-no-history": Case("R2 without history: clarify menu", scripts.R2_REQUEST, scripts.R2_NO_HISTORY),
    "R2-free-text": Case(f"R2 without history, then the free-text reply {scripts.R2_REPLY!r}", scripts.R2_REQUEST,
                         scripts.R2_FREE_TEXT),
    "R3": Case("R3, critical transfer: confirm", scripts.R3_REQUEST, scripts.R3),
    "R4": Case("R4, payments config over 3,000 files: execute", scripts.R4_REQUEST, scripts.R4),
    "R4-miss": Case("R4 with NONE_OF_THESE .4: widen, hierarchy, clarify(open)", scripts.R4_REQUEST, scripts.R4_MISS),
    "R4-found-in-bucket": Case("R4 miss whose file is the first option of widen bucket 0", scripts.R4_REQUEST,
                               runner=record_r4_bucket_hit),
    "R5": Case("R5, calendar event: confirm with an alternative", scripts.R5_REQUEST, scripts.R5),
    "R6": Case("R6 agent loop: read the latest ACME invoice, then forward it", scripts.R6_REQUEST,
               runner=record_r6(scripts.R6_STEP2)),
    "R6-refuse": Case("R6 had Jev followed the injected instruction: transfer_funds (refused)", scripts.R6_REQUEST,
                      runner=record_r6(scripts.R6_REFUSE_STEP2)),
    "R7": Case("R7, a joke: abstain", scripts.R7_REQUEST, scripts.R7),
}  # fmt: skip


def document(case: Case) -> dict[str, Any]:
    """The fixture document of a case."""
    doc: dict[str, Any] = {"note": NOTE.format(what=case.what), "request": case.request,
                           "model": scenario.SCENARIO_MODEL}  # fmt: skip
    if case.answers is not None:
        doc["answers"] = dict(case.answers)
    elif case.rounds:
        doc["rounds"] = [dict(r) for r in case.rounds]
    else:
        assert case.runner is not None
        doc["rounds"] = case.runner()
    return doc


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _answers(answers: Mapping[str, Any], indent: str) -> str:
    lines = [f"{indent}{_json(qid)}: {_json(spec)}" for qid, spec in answers.items()]
    return "{\n" + ",\n".join(lines) + "\n" + indent[:-2] + "}"


def render(doc: Mapping[str, Any]) -> str:
    """The document as JSON with one line per answer (diff-friendly)."""
    parts = []
    for key, value in doc.items():
        if key == "answers":
            text = _answers(value, "    ")
        elif key == "rounds":
            text = "[\n" + ",\n".join("    " + _answers(r, "      ") for r in value) + "\n  ]"
        else:
            text = _json(value)
        parts.append(f"  {_json(key)}: {text}")
    return "{\n" + ",\n".join(parts) + "\n}\n"


def render_all() -> dict[str, str]:
    """``{file name: content}`` of every generated fixture."""
    return {f"{name}.answers.json": render(document(case)) for name, case in CASES.items()}


def render_rows(rows: list[Any]) -> str:
    """A JSON list with one row per line."""
    return "[\n" + ",\n".join("  " + _json(row) for row in rows) + "\n]\n"


def render_proxy_data() -> dict[str, str]:
    """``{file name: content}`` of the proxy example's sources: 20 contacts (the eight §13.1 rows and twelve
    generated colleagues), the four accounts, and 300 workspace paths — all synthetic."""
    return {
        "contacts.json": render_rows(scenario.contact_rows(20)),
        "accounts.json": render_rows(scenario.ACCOUNT_ROWS),
        "files.json": render_rows(scenario.workspace_paths(300)),
    }


def outputs() -> dict[Path, str]:
    """Every generated file and its content."""
    files = {HERE / name: content for name, content in render_all().items()}
    files.update({PROXY_DATA / name: content for name, content in render_proxy_data().items()})
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate examples/fixtures/R*.answers.json.")
    parser.add_argument("--check", action="store_true", help="only check that the files are up to date")
    args = parser.parse_args(argv)
    stale = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.relative_to(HERE.parent).as_posix())
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    verb = "stale" if args.check else "written"
    print(f"{len(stale)} file(s) {verb}" + (f": {', '.join(stale)}" if stale else ""))
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
